[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
fastReruns = true
magicEnabled = true
postScriptGC = true

[client]
toolbarMode = "minimal"
showErrorDetails = true

[logger]
level = "error"
messageFormat = "%(message)s"

[theme]
primaryColor = "#22c55e"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#e2e8f0"
font = "sans serif"
